### ISSUE TITLE
Update Text-importer dependencies and documenation, and fix small associated bugs

### ISSUE THREAD

**Issue by piconti** [impresso/impresso-text-acquisition#121]
Like impresso-pycommons, impresso-text-acquisition was nut updated since the end of the Impresso I project, and is consequently in need of several updates.

In particular, several dependencies creating inconsistencies, and some documenation is outdated.
In addition, some small bugs have been uncovered in the code, along with bigger ones (which are the topic of individual issues:
- [x] BNL Ark ids: [issue about it](https://github.com/impresso/impresso-text-acquisition/issues/103)
- [x] codecs input/output error
- [x] Rero importer, image resolution field error
- [x] BNF-EN missing iiif links ([issue about it](https://github.com/impresso/impresso-text-acquisition/issues/102))
- [x] coords & iiif links in content items ([previous issue about it](https://github.com/impresso/impresso-text-acquisition/issues/104), [on rero](https://github.com/impresso/impresso-text-acquisition/issues/105)), [issue combining them](https://github.com/impresso/impresso-text-acquisition/issues/117)

The ones which do not have any specific related issue will be fixed along with the main dependencies update.
