### ISSUE TITLE
Edoardo summer contribution

### ISSUE THREAD

**Issue by e-maud** [impresso/impresso-text-acquisition#46]
#### Indicative planning
\# days to work: 24 days, to be done whenever between 15 July - 15 Sept.
1. [x] training and familiarisation with impresso code: 2 days (1 day = 8h)
2. [x] conversion/ingestion data RERO2: 8 days ([issue 49](https://github.com/impresso/impresso-text-acquisition/issues/49))
3. [x] refactoring of Olive importer ([issue 50](https://github.com/impresso/impresso-text-acquisition/issues/50))
4. [x] conversion/ingestion data Archives Basel: 6 days ([GDoc about status of data](https://docs.google.com/document/d/1bQUfhxKzJEmPmoLJ1UHXgpgT2XdyzQOJC03g-IAyc8Y/edit), [issue 52](https://github.com/impresso/impresso-text-acquisition/issues/52))
    - [x] finalize importer based on reply from content provider (pending)
    - [x] write a small stress test for SWA's IIIF ednpoint (TODO link)
5. [x] importer for BL data (not yet merged, reply pending) (issue #60)
~~5. [ ] retrieval/fix of image coordinates (3 days) OR conversion/ingestion of BNF data OR writing a series of tests (sanity checks) for converted data. TBD.~~

~~6. [ ] importer for Dutch (KB) newspapers data (issue #57)~~
7. [x] importer for BNF data (issue #56)

#### Tech details
RERO2 data is mounted on cluster36 in `/mnt/project_impresso/original/RERO2` (readonly).

**Comment by mromanello** [comment]
summer is over, lot of work was done by @ehoelzl, so this issue deserves to be closed
