### ISSUE TITLE
Edoardo winter contribution

### ISSUE THREAD

**Issue by mromanello** [impresso/impresso-text-acquisition#73]
## Text importer 

- [x] [Merged] bug in rero/Mets-alto importer: #72 
    - [x] rerun importer on RERO2 (all data on `original-canonical-testing`)
    - [x] rerun importer on RERO3 (all data on `original-canonical-testing`)
    - [ ] Treat images on multiple pages #83 
- [x] [Merged] finalize and thorough test of SWA importer: #52 
    - [x] Some issues are missing pages. Those issues are ignored and considered to be failed, and a log is outputted in the failed.log
    - [x] Some tokens have missing coordinates. This has been taken care of by ignoring them and adding a note to the page. #77 
    - [x] Run importer (all data on `original-canonical-testing`)
    - [x] Wait for missing pages to be sent and re-ingest.
- [Merged] finalize and test of BL importer: #60 
    - [x] Add IIIF link even though images don't exist yet
    - [ ] Was not possible to test on more recent issues to see if content items/images are correct; issue #84 open for later
- importer for BCUL newspapers #80
    - [x]  Get all journal names 
    - [x]  Get all `fs_path`
- [Merged] retain style information from BNL importer #81 
    - [x] Fix bug related to `section` #79 
    - [x] Fix Bug related to ads and images (ads show up as both)
         - Ads appear now only as ads, and duplicates are removed, while retaining the old content item id.
    - [x] Retain style information at page level
    - [x] Run Importer again (all data on `original-canonical-testing`)
- BNF importer: #56 (work can start on BNF batch and 3, see issue)
    - [x] Batch 1 ingestion (on `original-canonical-testing`)
    - [ ] Batch 2 ingestion
    - [ ] BNF Europeana

## Sanity check of contents:
- [x] `FedGazDe`
- [x] SWA newspapers

## Master DB

- import of BL metadata: [issue #59 (impresso-master-db)](https://github.com/impresso/impresso-master-db/issues/59)
- import BNF metadata
- import of Chronicling America (CA) metadata

**Comment by mromanello** [comment]
(closing this: still pending tasks have a dedicated issue open; all the rest was done)

Many thanks for your great work @ehoelzl !
